name: backend
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  path: ^1.8.0
  shelf: ^1.3.2
  shelf_modular: ^2.0.1
  shelf_swagger_ui: ^1.0.0+2
  json_annotation: ^4.6.0
  orm: ^2.0.1

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.21.5
